name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.x'
    - name: rake lint
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake lint
